server:
    port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/membership-management
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
